image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release-base-6:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-6
            - export BASE_VERSION=6
            - export DOCKER_REPO=atlassian/confluence-server
            - export DOCKERFILE_VERSION_STRING=CONFLUENCE_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=confluence
            - python /usr/src/app/create_release.py
  branches:
    base-6:
      - step:
          script:
            - git fetch --all
            - export BASE_BRANCH=base-6
            - export BASE_VERSION=6
            - export DOCKER_REPO=atlassian/confluence-server
            - export DOCKERFILE_VERSION_STRING=CONFLUENCE_VERSION
            - export GIT_USER=pipelinesagent
            - export GIT_EMAIL=pipelines-agent@atlassian.com
            - export MAC_PRODUCT_KEY=confluence
            - python /usr/src/app/update_release.py